### ISSUE TITLE
[기능] 예비후보자 목록 조회 & 선거구 조회

### ISSUE THREAD

**Issue by BryceYangS** [KoreanNationalElection/KoreaGeneralElection#11]
**예비후보자 목록**
---
- 예비후보자 목록 크롤링 가능
- 후보자 목록 메뉴 클릭시 좌측 메뉴 영역에 검색창이 뜸 (1. 모달? 2.메뉴 div 영역을 사용?)
- 선거구 선택 시 지도 하단 정보 표출 영역에 상하 스크롤로 정보 표출

**선거구 조회**
---
- issue : 현재 자신의 위치로만 선거구를 확인할 수 있음
- 행정동 검색 후 해당 선거구 layer 하이라이트 가능? 

**결정사안**
---
-  후보자 목록 메뉴 클릭 후 디자인 결정
    - 검색창을 어떻게 띄울 것인가?
- 행정동에 따른 선거구 조회 기능
    - 해당 선거구 layer만 하이라이트 가능?
- 현재 지도에 default로 20대 선거 결과가 나옴
    - 초기 화면은 선거구만 표출 ( 색상 X, 경계만 ) : geoJson layer 재사용 가능하지 않나..?

**Comment by EooHoSun** [comment]
### 예비후보자
1. 어짜피 예비후보자 중에 후보자로 넘어가는 사람이 많을테니깐 필요할듯
2. 예비후보자 크롤링 기능 필요

### 선거구 조회
1. 해당layer 하이라이트 / 깜빡이 가능

### 결정사안
1. 선거구 layer highlight  가능
2. geoJson 재사용 가능하나 여러 레이어 중첩표출 불가.
 ==> 중첩 필요 여부 검토 필요
